# Generated by Django 5.2.17 on 2026-10-02 15:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_learningsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, validators=[django.core.validators.URLValidator(schemes=['http', 'https'])], verbose_name='URL')),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('article', 'Article'), ('video', 'Video'), ('repo', 'Repo'), ('doc', 'Doc')], default='article', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='learning.goal')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
